/*-------------------------------------------------------------------*/
/* Et lite skript til å holde kodene til alle kortene - med navn     */
/*-------------------------------------------------------------------*/

//Array over navn: 
var kort_navn = 
    ["Ace of Clubs", "2 of Clubs", "3 of Clubs", "4 of Clubs",
    "5 of Clubs", "6 of Clubs", "7 of Clubs", "8 of Clubs", "9 of Clubs",
    "10 of Clubs", "Jack of Clubs", "Queen of Clubs", "King of Clubs",
    "Ace of Diamonds", "2 of Diamonds", "3 of Diamonds", "4 of Diamonds",
    "5 of Diamonds", "6 of Diamonds", "7 of Diamonds", "8 of Diamonds", "9 of Diamonds",
    "10 of Diamonds", "Jack of Diamonds", "Queen of Diamonds", "King of Diamonds",
    "Ace of Hearts", "2 of Hearts", "3 of Hearts", "4 of Hearts",
    "5 of Hearts", "6 of Hearts", "7 of Hearts", "8 of Hearts", "9 of Hearts",
    "10 of Hearts", "Jack of Hearts", "Queen of Hearts", "King of Hearts",
    "Ace of Spades", "2 of Spades", "3 of Spades", "4 of Spades",
    "5 of Spades", "6 of Spades", "7 of Spades", "8 of Spades", "9 of Spades",
    "10 of Spades", "Jack of Spades", "Queen of Spades", "King of Spades"];

//Assosiativt array over kortene
var kort_array_navn = 
    {   c14: "Ace of Clubs", 
        c2: "2 of Clubs", 
        c3: "3 of Clubs", 
        c4: "4 of Clubs",
        c5: "5 of Clubs", 
        c6: "6 of Clubs", 
        c7: "7 of Clubs", 
        c8: "8 of Clubs", 
        c9: "9 of Clubs",
        c10: "10 of Clubs", 
        c11: "Jack of Clubs", 
        c12: "Queen of Clubs", 
        c13: "King of Clubs",
        d14: "Ace of Diamonds", 
        d2: "2 of Diamonds", 
        d3: "3 of Diamonds", 
        d4: "4 of Diamonds",
        d5: "5 of Diamonds", 
        d6: "6 of Diamonds", 
        d7: "7 of Diamonds", 
        d8: "8 of Diamonds", 
        d9: "9 of Diamonds",
        d10: "10 of Diamonds", 
        d11: "Jack of Diamonds", 
        d12: "Queen of Diamonds", 
        d13: "King of Diamonds",
        h14: "Ace of Hearts", 
        h2: "2 of Hearts", 
        h3: "3 of Hearts", 
        h4: "4 of Hearts",
        h5: "5 of Hearts", 
        h6: "6 of Hearts", 
        h7: "7 of Hearts", 
        h8: "8 of Hearts", 
        h9: "9 of Hearts",
        h10: "10 of Hearts", 
        h11: "Jack of Hearts", 
        h12: "Queen of Hearts", 
        h13: "King of Hearts",
        s14: "Ace of Spades", 
        s2: "2 of Spades", 
        s3: "3 of Spades", 
        s4: "4 of Spades",
        s5: "5 of Spades", 
        s6: "6 of Spades", 
        s7: "7 of Spades", 
        s8: "8 of Spades", 
        s9: "9 of Spades",
        s10: "10 of Spades", 
        s11: "Jack of Spades", 
        s12: "Queen of Spades", 
        s13: "King of Spades"};

